# Site settings
title: A blog about lorem ipsum dolor sit amet
description: A blog about lorem ipsum dolor sit amet

baseurl: "/cv"

# User settings
username: Oscar Marie--Taillefer
user_description: Bicycle rights irony actually neutra typewriter lyft. Man bun taxidermy put a bird on it, umami yr ramps pop-up ugh bushwick chia lo-fi. Occupy bitters pour-over snackwave you probably haven't heard of them small batch. Cornhole mustache man bun letterpress echo park VHS.
user_title: Elève ingénieur
email: o5mariet@enib.fr
github_username: ryshu

# Google-analytics
google-analytics:
  id: ""

exclude: ["package.json", "src", "node_modules"]
destination: ./docs
